### ISSUE TITLE
How to compress all files in all subfolders with one extension : so ???

### ISSUE THREAD

**Issue by UnrealKaraulov** [edgarrc/action-7z#5]
How to compress all files in all subfolders with one extension : so ???

**Comment by edgarrc** [comment]
The example given in the readme does just that:

```
7z a -t7z -mx=9 build.7z ./build/
```

It will compress all files inside ./build into buil.zip

If you want to filter by file extensions, checkout the -x parameter, for instance: -x!*.avi -x!*.pdb

https://linux.die.net/man/1/7z
